fixup version numbers

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2310,8 +2310,8 @@ if test "$ns_version_ok" = "yes"; then
 	echo "$as_me:$LINENO: result: Compatible version" >&5
 echo "${ECHO_T}Compatible version" >&6;
 else
-	{ { echo "$as_me:$LINENO: error: This module requires NeoStats 3.0.a3-dev or higher" >&5
-echo "$as_me: error: This module requires NeoStats 3.0.a3-dev or higher" >&2;}
+	{ { echo "$as_me:$LINENO: error: This module requires NeoStats 3.0.a3 or higher" >&5
+echo "$as_me: error: This module requires NeoStats 3.0.a3 or higher" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
