rewrite for playing in multiple channels see ChangeLog for details

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1259,7 +1259,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 PACKAGE=YahtzeeServ
 MODULE_MAJOR=3
 MODULE_MINOR=0
-MODULE_REV=a2
+MODULE_REV=a3-dev
 VERSION=$MODULE_MAJOR.$MODULE_MINOR.$MODULE_REV
 cat >>confdefs.h <<_ACEOF
 #define MODULE_VERSION "$VERSION"
@@ -2310,8 +2310,8 @@ if test "$ns_version_ok" = "yes"; then
 	echo "$as_me:$LINENO: result: Compatible version" >&5
 echo "${ECHO_T}Compatible version" >&6;
 else
-	{ { echo "$as_me:$LINENO: error: This module requires NeoStats 3.0.a2 or higher" >&5
-echo "$as_me: error: This module requires NeoStats 3.0.a2 or higher" >&2;}
+	{ { echo "$as_me:$LINENO: error: This module requires NeoStats 3.0.a3-dev or higher" >&5
+echo "$as_me: error: This module requires NeoStats 3.0.a3-dev or higher" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -4303,7 +4303,5 @@ echo "Configuration complete."
 read -p "Press Enter key to read the release notes"
 clear
 more RELNOTES
-echo "This Module was written by:"
-echo "	DeadNotBurried (dnb@majestic-liaisons.com)"
-echo "Run 'make' (or 'gmake' on some systems) to compile NeoStats."
+echo "Run 'make' (or 'gmake' on some systems) to compile."
 echo "If you require support, see the README file."
